# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-java:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build and Test with Gradle
      run: |
        ./gradlew clean test

    - name: Build with Gradle
      run: ./gradlew build
       
  
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    -  name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Add execute permissions recursively
      run: find   ./build/libs  -type d -exec chmod +x {} \;      
    - name: Add execute permission
      run: chmod go+rx ./build/libs
    - name: chnage owner name
      run: chown docker:docker  ./build/libs
  
    - name: List Contents of Directory
      run: |
          ls -l ./build/libs        
      
    -  name: Build and push
       uses: docker/build-push-action@v4
       with:
          context: .
          push: true
          tags: maheshdandu/new-app:latest
      
           
   
      




  
      
    

    


  
         
